type Enumerate<N extends number, Acc extends number[] = []> = Acc['length'] extends N ? Acc[number] : Enumerate<N, [...Acc, Acc['length']]>;
type IntRange<F extends number, T extends number> = Exclude<Enumerate<T>, Enumerate<F>>;
type allowedDateFormat = 'DMY' | 'DYM' | 'MDY' | 'MYD' | 'YDM' | 'YMD';
type allowedTimeFormat = 'HMS' | 'HSM' | 'MHS' | 'MSH' | 'SHM' | 'SMH';
type allowedLanguages = 'en' | 'en-US' | 'en-GB' | 'en-AU' | 'en-CA' | 'en-IN' | 'en-NZ' | 'en-ZA' | 'ar' | 'ar-AE' | 'ar-BH' | 'ar-DZ' | 'ar-EG' | 'ar-IQ' | 'ar-JO' | 'ar-KW' | 'ar-LB' | 'ar-LY' | 'ar-MA' | 'ar-OM' | 'ar-QA' | 'ar-SA' | 'ar-SY' | 'ar-TN' | 'ar-YE' | 'bn' | 'bn-BD' | 'bn-IN' | 'cs' | 'cs-CZ' | 'da' | 'da-DK' | 'de' | 'de-AT' | 'de-CH' | 'de-DE' | 'de-LI' | 'de-LU' | 'el' | 'el-GR' | 'en-IE' | 'en-MT' | 'es' | 'es-AR' | 'es-BO' | 'es-CL' | 'es-CO' | 'es-CR' | 'es-DO' | 'es-EC' | 'es-ES' | 'es-GT' | 'es-HN' | 'es-MX' | 'es-NI' | 'es-PA' | 'es-PE' | 'es-PR' | 'es-PY' | 'es-SV' | 'es-UY' | 'es-VE' | 'et' | 'et-EE' | 'fa' | 'fa-IR' | 'fi' | 'fi-FI' | 'fil' | 'fil-PH' | 'fr' | 'fr-BE' | 'fr-CA' | 'fr-CH' | 'fr-FR' | 'fr-LU' | 'fr-MC' | 'he' | 'he-IL' | 'hi' | 'hi-IN' | 'hr' | 'hr-HR' | 'hu' | 'hu-HU' | 'id' | 'id-ID' | 'it' | 'it-CH' | 'it-IT' | 'ja' | 'ja-JP' | 'ko' | 'ko-KR' | 'lt' | 'lt-LT' | 'lv' | 'lv-LV' | 'ms' | 'ms-MY' | 'nl' | 'nl-BE' | 'nl-NL' | 'no' | 'no-NO' | 'pl' | 'pl-PL' | 'pt' | 'pt-BR' | 'pt-PT' | 'ro' | 'ro-RO' | 'ru' | 'ru-RU' | 'sk' | 'sk-SK' | 'sl' | 'sl-SI' | 'sr' | 'sr-RS' | 'sv' | 'sv-SE' | 'th' | 'th-TH' | 'tr' | 'tr-TR' | 'uk' | 'uk-UA' | 'vi' | 'vi-VN' | 'zh' | 'zh-CN' | 'zh-HK' | 'zh-TW';
export declare class ShkDate {
    private _date;
    private _dateFormat;
    private _timeFormat;
    private _dateSeparator;
    private _timeSeparator;
    private _fillZeros;
    private _language;
    private _checkIrregular;
    private _jsYear;
    private _jsMonth;
    private _jsDay;
    private _jsHour;
    private _jsMinute;
    private _jsSecond;
    constructor(date?: string);
    private updateJSDate;
    get dateFormat(): allowedDateFormat;
    getDateFormat(): allowedDateFormat;
    set dateFormat(dateFormat: allowedDateFormat);
    setDateFormat(dateFormat: allowedDateFormat): void;
    get timeFormat(): allowedTimeFormat;
    getTimeFormat(): allowedTimeFormat;
    set timeFormat(timeFormat: allowedTimeFormat);
    setTimeFormat(timeFormat: allowedTimeFormat): void;
    get dateSeparator(): string;
    getDateSeparator(): string;
    set dateSeparator(dateSeparator: string);
    setDateSeparator(dateSeparator: string): void;
    get timeSeparator(): string;
    getTimeSeparator(): string;
    set timeSeparator(timeSeparator: string);
    setTimeSeparator(timeSeparator: string): void;
    get fillZeros(): boolean;
    getFillZeros(): boolean;
    set fillZeros(fillZeros: boolean);
    setFillZeros(fillZeros: boolean): void;
    set language(language: allowedLanguages);
    setLanguage(language?: allowedLanguages): void;
    get year(): number | string;
    getYear(): number | string;
    set year(year: number | string);
    setYear(year: number | string): void;
    get month(): IntRange<1, 13> | string;
    getMonth(): IntRange<1, 13> | string;
    set month(month: IntRange<1, 13> | string);
    setMonth(month: IntRange<1, 13> | string): void;
    get day(): IntRange<1, 32> | string;
    getDay(): IntRange<1, 32> | string;
    set day(day: IntRange<1, 32> | string);
    setDay(day: IntRange<1, 32> | string): void;
    get hours(): IntRange<0, 24> | string;
    getHours(): IntRange<0, 24> | string;
    set hours(hours: IntRange<0, 24> | string);
    setHours(hours: IntRange<0, 24> | string): void;
    get minutes(): IntRange<0, 60> | string;
    getMinutes(): IntRange<0, 60> | string;
    set minutes(minutes: IntRange<0, 60> | string);
    setMinutes(minutes: IntRange<0, 60> | string): void;
    get seconds(): IntRange<0, 60> | string;
    getSeconds(): IntRange<0, 60> | string;
    set seconds(seconds: IntRange<0, 60> | string);
    setSeconds(seconds: IntRange<0, 60> | string): void;
    get date(): string;
    getDate(): string;
    set date(date: string);
    setDate(date: string): void;
    get time(): string;
    getTime(): string;
    set time(time: string);
    setTime(time: string): void;
    get dateTime(): string;
    getDateTime(): string;
    set dateTime(dateTime: string);
    setDateTime(dateTime: string): void;
    get extMonth(): string;
    getExtMonth(): string;
    get weekDay(): string;
    getWeekDay(): string;
}
export {};
